---
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/prafullkulshrestha/Microservices-With-Spring
          search-paths: ConfigData
server:
  port: 8001

              